replace "echo -e" with "printf" for better compatiblity.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,64 +32,65 @@ fi
 
 MAKE=`whereis -b make | awk '{print $2}'`
 ECHO=`whereis -b echo | awk '{print $2}'`
+PRINTF=`whereis -b printf | awk '{print $2}'`
 
 ERR()
 {
-  $ECHO -e "\x1b[1;31m""$1""\x1b[0m" >&2
+  $PRINTF "\x1b\x5b1;31m$1\x1b\x5b0m" >&2
 }
 
 WARN()
 {
-  $ECHO -e "\x1b[1;35m""$1""\x1b[0m"
+  $PRINTF "\x1b\x5b1;35m$1\x1b\x5b0m"
 }
 
 INFO()
 {
-  $ECHO -e "\x1b[1;36m""$1""\x1b[0m"
+  $PRINTF "\x1b\x5b1;36m$1\x1b\x5b0m"
 }
 
 IMPORTANT()
 {
-  $ECHO -e "\x1b[1;33m""$1""\x1b[0m"
+  $PRINTF "\x1b\x5b1;33m$1\x1b\x5b0m"
 }
 
 NORMAL()
 {
-  $ECHO -e "\x1b[1;32m""$1""\x1b[0m"
+  $PRINTF "\x1b\x5b1;32m$1\x1b\x5b0m"
 }
 
 if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "-help" ]; then
-  WARN "Usage: $0 [OPTION]... [VAR=VALUE]..."
+  WARN "Usage: $0 [OPTION]... [VAR=VALUE]...\n"
   $ECHO ""
   $ECHO "Installation directories:"
-  $ECHO -e "  `INFO '--prefix=PREFIX'`     : install in PREFIX (e.g. /usr) `NORMAL '[default: /usr/local]'`"
-  $ECHO -e "  `INFO '--sysconfdir=ETCDIR'` : system conf file install dir `NORMAL '[default: $PREFIX/etc/xdg]'`"
+  $ECHO "  `INFO '--prefix=PREFIX'`     : install in PREFIX (e.g. /usr) `NORMAL '[default: /usr/local]'`"
+  $ECHO "  `INFO '--sysconfdir=ETCDIR'` : system conf file install dir `NORMAL '[default: $PREFIX/etc/xdg]'`"
   $ECHO ""
   $ECHO "Optional Packages:"
-  $ECHO -e "  `INFO '--with-gtk=2.0|3.0'`  : which gtk+ version to compile against `NORMAL '[default: 2.0]'`"
+  $ECHO "  `INFO '--with-gtk=2.0|3.0'`  : which gtk+ version to compile against `NORMAL '[default: 2.0]'`"
   $ECHO ""
   $ECHO "Optional Features:"
-  $ECHO -e "  `INFO '--enable-debug'`      : enable debug mode `NORMAL '[default: disable]'`"
-  $ECHO -e "  `INFO '--disable-nls'`       : disable Native Language Support `NORMAL '[default: enable]'`"
-  $ECHO -e "  `INFO '--disable-safe-mode'` : disable run in safe mode `NORMAL '[default: enable]'`"
+  $ECHO "  `INFO '--enable-debug'`      : enable debug mode `NORMAL '[default: disable]'`"
+  $ECHO "  `INFO '--disable-nls'`       : disable Native Language Support `NORMAL '[default: enable]'`"
+  $ECHO "  `INFO '--disable-safe-mode'` : disable run in safe mode `NORMAL '[default: enable]'`"
   $ECHO ""
-  $ECHO -e "run \``IMPORTANT 'make'`' to build $PACKAGE, include binary, data and translations."
-  $ECHO -e "run \``IMPORTANT 'make src'`' to build $PACKAGE binary files."
-  $ECHO -e "run \``IMPORTANT 'make data'`' to build $PACKAGE data files."
-  $ECHO -e "run \``IMPORTANT 'make po'`' to build $PACKAGE translation files."
+  $ECHO "run \``IMPORTANT 'make'`' to build $PACKAGE, include binary, data and translations."
+  $ECHO "run \``IMPORTANT 'make src'`' to build $PACKAGE binary files."
+  $ECHO "run \``IMPORTANT 'make data'`' to build $PACKAGE data files."
+  $ECHO "run \``IMPORTANT 'make po'`' to build $PACKAGE translation files."
   $ECHO ""
-  $ECHO -e "run \``IMPORTANT 'make clean'`' to clean $PACKAGE builded files."
-  $ECHO -e "run \``IMPORTANT 'make distclean'`' to clean $PACKAGE builded and configure files."
+  $ECHO "run \``IMPORTANT 'make clean'`' to clean $PACKAGE builded files."
+  $ECHO "run \``IMPORTANT 'make distclean'`' to clean $PACKAGE builded and configure files."
   $ECHO ""
-  $ECHO -e "run \``IMPORTANT 'make install'`' to install $PACKAGE to your system."
-  $ECHO -e "run \``IMPORTANT 'make uninstall'`' to unstall $PACKAGE in `NORMAL "$PREFIX"` from your system."
+  $ECHO "run \``IMPORTANT 'make install'`' to install $PACKAGE to your system."
+  $ECHO "run \``IMPORTANT 'make uninstall'`' to unstall $PACKAGE in `NORMAL "$PREFIX"` from your system.\n"
   exit 0
 fi
 
 PKGCONFIG=`whereis -b pkg-config | awk '{print $2}'`
 if [ -z "$PKGCONFIG" ]; then
   $ECHO ""
-  ERR "ERROR: pkg-config package is needed to run this configure script. ABORT!"
+  ERR "ERROR: pkg-config package is needed to run this configure script. ABORT!\n"
   $ECHO ""
   exit 1
 fi
@@ -130,7 +131,7 @@ $ECHO ""
 
 $PKGCONFIG --exists 'glib-2.0 >= 2.12' > /dev/null 2>&1
 if [ $? != 0 ]; then
-  ERR "ERROR: Glib > 2.12 is needed to build $PACKAGE."
+  ERR "ERROR: Glib > 2.12 is needed to build $PACKAGE.\n"
   $ECHO ""
   exit 1
 fi
@@ -151,17 +152,17 @@ if [ $? != 0 ]; then
     $ECHO -n "... testing GTK+3    : "
     $PKGCONFIG --cflags $GTK > /dev/null 2>&1
     if [ $? != 0 ]; then
-      ERR "not found. Please install libgtk2.0-dev/libgtk-3-dev package. ABORT!"
+      ERR "not found. Please install libgtk2.0-dev/libgtk-3-dev package. ABORT!\n"
       $ECHO ""
       exit 1
     else
-      INFO "found."
+      INFO "found.\n"
     fi
   else
     if [ "$GTK" = "gtk+-2.0" ]; then
-      ERR "not found. Please install libgtk2.0-dev package. ABORT!"
+      ERR "not found. Please install libgtk2.0-dev package. ABORT!\n"
     else
-      ERR "not found. Please install libgtk-3-dev package. ABORT!"
+      ERR "not found. Please install libgtk-3-dev package. ABORT!\n"
     fi
     $ECHO ""
     exit 1
@@ -170,19 +171,19 @@ else
   if [ "$GTK" = gtk+-2.0 ]; then
     $PKGCONFIG --exists 'gtk+-2.0 >= 2.8' > /dev/null 2>&1
     if [ $? != 0 ]; then
-      ERR "ERROR: Gtk+2 > 2.8 is needed to build $PACKAGE."
+      ERR "ERROR: Gtk+2 > 2.8 is needed to build $PACKAGE.\n"
       $ECHO ""
       exit 1
     fi
 
     $PKGCONFIG --exists 'gtk+-2.0 < 2.12' > /dev/null 2>&1
     if [ $? != 0 ]; then
-      INFO "found."
+      INFO "found.\n"
     else
-      WARN "found. But using Gtk+2 > 2.12 is recommend to build $PACKAGE."
+      WARN "found. But using Gtk+2 > 2.12 is recommend to build $PACKAGE.\n"
     fi
   else
-    WARN "found. But using Gtk+3 to build $PACKAGE is NOT recommend."
+    WARN "found. But using Gtk+3 to build $PACKAGE is NOT recommend.\n"
   fi
 fi
 
@@ -200,9 +201,9 @@ fi
 $PKGCONFIG --cflags $VTE > /dev/null 2>&1
 if [ $? != 0 ]; then
   if [ "$GTK" = 'gtk+-2.0' ]; then
-    ERR "not found. Please install libvte-dev package. ABORT!"
+    ERR "not found. Please install libvte-dev package. ABORT!\n"
   else
-    ERR "not found. Please install libvte-2.90-dev package. ABORT!"
+    ERR "not found. Please install libvte-2.90-dev package. ABORT!\n"
   fi
   $ECHO ""
   exit 1
@@ -210,13 +211,13 @@ else
   if [ "$GTK" = 'vte' ]; then
     $PKGCONFIG --exists 'vte >= 0.12' > /dev/null 2>&1
     if [ $? != 0 ]; then
-      ERR "ERROR: VTE > 0.12 is needed to build $PACKAGE."
+      ERR "ERROR: VTE > 0.12 is needed to build $PACKAGE.\n"
       $ECHO ""
       exit 1
     fi
   fi
 
-  INFO "found."
+  INFO "found.\n"
 fi
 
 
@@ -226,9 +227,9 @@ if [ "$NLS" = 'Y' ]; then
   $ECHO -n "... testing Native Language Support : "
   GETTEST=`whereis -b gettext | awk '{print $2}'`
   if [ $? != 0 ]; then
-    ERR "not found. Please install gettext package. ABORT!"
+    ERR "not found. Please install gettext package. ABORT!\n"
   else
-    INFO "found."
+    INFO "found.\n"
   fi
 fi
 
@@ -239,10 +240,10 @@ if [ "$GNOME_CONTROL_CENTER" = 'Y' ]; then
   $ECHO -n "... testing Gnome Control Center    : "
   GNOME_CONTROL_CENTER_DIR=`pkg-config --variable=defappsdir --define-variable=datadir='$(DATADIR)' gnome-default-applications`
   if [ $? != 0 ]; then
-    WARN "not found."
+    WARN "not found.\n"
     GNOME_CONTROL_CENTER=N
   else
-    INFO "found."
+    INFO "found.\n"
   fi
 fi
 
@@ -250,13 +251,13 @@ $ECHO ""
 
 # ---- REPORT ---- #
 
-INFO "==========================================="
+INFO "===========================================\n"
 $ECHO "PACKAGE   = $PACKAGE"
 $ECHO "BINARY    = $BINARY"
 $ECHO "VERSION   = $VERSION"
 $ECHO "BUGREPORT = $BUGREPORT"
-IMPORTANT "PREFIX    = $PREFIX"
-IMPORTANT "ETCDIR    = $ETCDIR"
+IMPORTANT "PREFIX    = $PREFIX\n"
+IMPORTANT "ETCDIR    = $ETCDIR\n"
 $ECHO "BINDIR    = $BINDIR"
 $ECHO "DATADIR   = $DATADIR"
 $ECHO "MANDIR    = $MANDIR"
@@ -266,17 +267,17 @@ if [ "$NLS" = 'Y' ]; then
 fi
 $ECHO "ICONDIR   = $ICONDIR"
 if [ "$DEBUG" = 'Y' ]; then
-  IMPORTANT "DEBUG     = $DEBUG"
+  IMPORTANT "DEBUG     = $DEBUG\n"
 else
   $ECHO "DEBUG     = $DEBUG"
 fi
 if [ "$NLS" = 'N' ]; then
-  IMPORTANT "NLS       = $NLS"
+  IMPORTANT "NLS       = $NLS\n"
 else
   $ECHO "NLS       = $NLS"
 fi
 if [ "$SAFEMODE" = 'N' ]; then
-  IMPORTANT "SAFEMODE  = $SAFEMODE"
+  IMPORTANT "SAFEMODE  = $SAFEMODE\n"
 else
   $ECHO "SAFEMODE  = $SAFEMODE"
 fi
@@ -286,28 +287,28 @@ if [ -n "$CHECK_CC" ]; then
   if [ "$CC" = 'gcc' ]; then
     $ECHO "CC        = $CC"
   else
-    IMPORTANT "CC        = $CC"
+    IMPORTANT "CC        = $CC\n"
   fi
 else
-  ERR "CC        = $CC"
+  ERR "CC        = $CC\n"
 fi
 if [ "$CFLAGS" != '-Wall -O -g' ]; then
-  IMPORTANT "CFLAGS    = $CFLAGS"
+  IMPORTANT "CFLAGS    = $CFLAGS\n"
 else
   $ECHO "CFLAGS    = $CFLAGS"
 fi
 if [ -n "$MAKE" ]; then
   $ECHO "MAKE      = $MAKE"
 else
-  ERR "MAKE      = $MAKE"
+  ERR "MAKE      = $MAKE\n"
 fi
 $ECHO "GTK       = $GTK"
 $ECHO "VTE       = $VTE"
 if [ "$GNOME_CONTROL_CENTER" = 'Y' ]; then
-  IMPORTANT "GNOME_CONTROL_CENTER = $GNOME_CONTROL_CENTER"
-  IMPORTANT "GNOME_CONTROL_CENTER_DIR = $GNOME_CONTROL_CENTER_DIR"
+  IMPORTANT "GNOME_CONTROL_CENTER = $GNOME_CONTROL_CENTER\n"
+  IMPORTANT "GNOME_CONTROL_CENTER_DIR = $GNOME_CONTROL_CENTER_DIR\n"
 fi
-INFO "==========================================="
+INFO "===========================================\n"
 $ECHO ""
 
 $ECHO "PACKAGE = $PACKAGE" > .config
