Revert baab0435fdde3d2686058246af26d01c0c9210bd.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -128,7 +128,9 @@ for opt do
       ;;
     *)
       $ECHO ""
-      WARN "WARNING: invalid option \"$opt\"!\n"
+      ERR "ERROR: invalid option \"$opt\". ABORT!\n"
+      $ECHO ""
+      exit 1
       ;;
   esac
 done
