Better compatible with vte >= 0.38.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -83,9 +83,22 @@ CHECK_MESSAGE()
 
 PACKAGE_MESSAGE()
 {
-  ERR "\n\n  Please install \""
-  WARN "$*"
-  ERR "\" package. ABORT!\n\n"
+  ERR "\n\n  Please install "
+  COUNT_PKG=1
+  for PKG in $*; do
+    if [ $COUNT_PKG -ge 2 ]; then
+      if [ $COUNT_PKG -eq $# ]; then
+	ERR " or "
+      else
+	ERR ", "
+      fi
+    fi
+    ERR "\""
+    WARN "$PKG"
+    ERR "\""
+  COUNT_PKG=$(($COUNT_PKG+1))
+  done
+  ERR " package. ABORT!\n\n"
 }
 
 VERSION_MESSAGE()
@@ -202,7 +215,7 @@ fi
 $PKGCONFIG --cflags $GTK > /dev/null 2>&1
 if [ $? != 0 ]; then
   if [ "$GTK" = "gtk+-2.0" -a $GTK_SPC -eq 0 ]; then
-    $ECHO "[NO]. Trying GTK+3..."
+    $ECHO "[NO]. Trying GTK+3 ..."
     GTK=gtk+-3.0
     CHECK_MESSAGE 'GTK+3'
     $PKGCONFIG --cflags $GTK > /dev/null 2>&1
@@ -260,11 +273,20 @@ if [ $? != 0 ]; then
   if [ "$GTK" = 'gtk+-2.0' ]; then
     ERR "[NG]"
     PACKAGE_MESSAGE "libvte-dev"
+    exit 1
   else
-    ERR "[NG]"
-    PACKAGE_MESSAGE "libvte-2.90-dev"
+    $ECHO "[NO]. Trying VTE 0.38 ..."
+    VTE=vte-2.91
+    CHECK_MESSAGE 'VTE 0.38'
+    $PKGCONFIG --cflags $VTE > /dev/null 2>&1
+    if [ $? != 0 ]; then
+      ERR "[NG]"
+      PACKAGE_MESSAGE "libvte-2.90-dev" "libvte-2.91-dev"
+      exit 1
+    else
+      INFO "[OK]\n"
+    fi
   fi
-  exit 1
 else
   if [ "$VTE" = 'vte' ]; then
     $PKGCONFIG --exists 'vte >= 0.12' > /dev/null 2>&1
@@ -273,21 +295,20 @@ else
       VERSION_MESSAGE "\n\n" "VTE" "0.12"
       exit 1
     fi
-    BACKGROUND=N
-  else
-    $PKGCONFIG --exists 'vte < 0.34.8' > /dev/null 2>&1
-    if [ $? = 0 ]; then
-      BACKGROUND=N
-    fi
-    $PKGCONFIG --exists 'vte < 0.37.0' > /dev/null 2>&1
-    if [ $? = 0 ]; then
-      BACKGROUND=N
-    fi
   fi
 
   INFO "[OK]\n"
 fi
 
+$PKGCONFIG --exists "$VTE < 0.34.8" > /dev/null 2>&1
+if [ $? = 0 ]; then
+  BACKGROUND=N
+fi
+
+$PKGCONFIG --exists "$VTE >= 0.38.0" > /dev/null 2>&1
+if [ $? = 0 ]; then
+  BACKGROUND=N
+fi
 
 # ---- NLS ---- #
 
